<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Cadastro</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet"  type="text/css" href="../../public/css/cadastro.css">
    </head>
    <body>
        <header>
            <div class="container">
                <nav class="navbar navbar-expand-lg">
                    <h1>NoobDiario</h1> 
                    <div class="collapse navbar-collapse justify-content-end" id="navbar-links">
                        <div class="navbar-nav">
                            <a class="nav-item nav-link active " href="http://localhost:8080/login" id="sair" >Login</a>                       
                        </div>
                    </div>
                </nav>            
            </div>
        </header>
        <hr>
        <br>
        
        <section class="content">
            <div class="cadastro">
                
                <form class="form" method="POST" action="/cadastro">
                    
                    <a>Nome:</a>

                    <?php if(isset($get)) {?>
                    <!-- o name server para o array visualizar o nome da variável enviado pelo imput -->
                        <input class="field" name="nome"  placeholder="Nome">
                        <br>
                        <a>CPF:</a>   
                        <input class="field" name="cpf" placeholder="CPF">
                        <br>
                        <a>Telefone:</a>   
                        <input class="field" name="telefone" placeholder="(xx)xxxx-xxxx">
                        <br>
                        <h6>Dados de acesso:</h6>
                        <a>E-mail:</a>   
                        <input class="field" name="email" placeholder="E-mail">
                        <br>
                        <a>Senha:</a>
                        <input class="senha" type="password" name="senha" placeholder="Senha">  
                        <a>Confirme senha:</a> 
                        <input class="senha" type="password" name="confirm_senha" placeholder="Confirma senha">
                          
                        <!-- não precisa colocar NAME no botão, se não você vai enviar essa informação no formulario -->
                        <button class="botao" type="submit">Cadastrar</button> 
                   
                    <?php }else{ ?>
                                
                          <?php if(isset($nome)){ 
                                    
                                    echo "<b style=color:red> * Nome vazio </b>"; 
                                }?>

                                <input class="field" name="nome"  placeholder="Nome" value="<?=$dados['nome']?>">
                                <br>

                                <a>CPF:</a> 
                          <?php if(isset($cpf)){
                              
                                    echo "<b style=color:red> * CPF invalido </b>";
                                } ?>
                                <input class="field" name="cpf" placeholder="CPF" value="<?=$dados['cpf']?>">
                                <br>
                                <a>Telefone:</a> 
                                <?php if(isset($tel)){
                                    
                                    echo "<b style=color:red> * Telefone invalido </b>";
                                } ?>  
                                <input class="field" name="telefone" placeholder="(xx)xxxx-xxxx" value="<?=$dados['telefone']?>">
                                <br>
                                <h6>Dados de acesso:</h6>
                                <a>E-mail:</a>
                                <?php if(isset($email)){
                                    
                                    echo "<b style=color:red> * E-mail invalido </b>";
                                }
                                if(isset($emailDuplicado)){
                                    
                                    echo "<b style=color:red> * E-mail já cadatrado </b>";
                                } ?>    
                                <input class="field" name="email" placeholder="E-mail" value="<?=$dados['email']?>" >
                                <br>
                                <a>Senha:</a>
                                <?php if(isset($senha)){
                                        if(empty($senha) || strlen($senha) < 8){
                                            echo "<b style=color:red> *Senha no minimo com 8 caracteres</b>";
                                        }else{
                                            echo "<b style=color:red> *Senhas diferentes</b>";
                                        }
                                }?>  
                                <input class="senha" type="password" name="senha" placeholder="Senha">
                                <a>Confirme senha:</a> 
                                <input class="senha" type="password" name="confirm_senha" placeholder="Confirma senha">
                                <button class="botao" type="submit">Cadastrar</button> 
                    <?php   
                         }?>
                    
                    
                          
                </form>
            </div>
        </section>
<?php