<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet"  type="text/css" href="../../public/css/diario.css">
    </head>
    <body>
        <header>
            <div class="container">
                <nav class="navbar navbar-expand-lg">
                    <h1>NoobDiario</h1> 
                    <div class="collapse navbar-collapse justify-content-end" id="navbar-links">
                        <div class="navbar-nav">
                            <a class="nav-item nav-link active " href="http://localhost:8080/login" id="sair" >Sair</a>                       
                        </div>
                    </div>
                </nav>            
            </div>
        </header>
        <hr>
        <br>
        <?php if(isset($update)){ ?>
            
                <section class="content">
                    <div class="Anotacao">
                
                        <?php if(isset($vazio)){;?>
                            <b style=color:red align="center"> * Anotação vazia </b>
                        <?php } ?>
                                           
                        <h6>Editar:</h6>
                         <table border width='100%' height="15%" align="center">
                            <tr>
                                <td align='center'> <br> <?= $update['anotacao'] ?> </br><br></td>
                            </tr>
                        </table>
                            <br>
                            <form class="form" method="POST" action="/diario">
                                <input class="field" name="anotacao" align-text="center" placeholder="<?=$update['anotacao']?>">    
                                <div class="bt">
                                    <button class="botao" type="imput" name="update" value="<?=$update['id']?>">Editar</button> 
                                </div>      
                            </form>
                    </div>
                </section> 
                      

        <?php }else{ ?>
            
            <section class="content">
                <div class="Anotacao">
                    <h6>Anotação:</h6>
                    <?php if(isset($texto)){ ?>
                        <b style=color:red align="center"> * Anotação vazia </b> 
                    <?php } ?>
                        
                    <form class="form" method="POST" action="/diario">
                        <input class="field" name="anotacao" placeholder="O que você está pensando ?">    
                        <div class="bt">
                            <button class="botao" type="imput">Enviar</button> 
                        </div>      
                    </form>
                </div>
            </section>
              
            <?php foreach($anotacao as $anota){ ?>
 
                <section class='content'>
                    <div class='Anotacao'>
                        <h6><b>Anotação:  </b></h6> <?= $anota['id']; ?>     /  <?= $anota['dia']; ?>
                        <table border width='100%' height="15%" align="center">
                            <form class='form' method='POST' action='/diario/edita' id='form'>
                            <tr>
                                <td align='center'> <br> <?= $anota['anotacao'] ?> </br><br></td>
                            </tr>
                        </table>
                        <button class='botao' type='submit' form='form' name='editar' value="<?= $anota['id']?>"> Editar </button>
                        <button class='botao1'  type='submit' form='form' name='excluir' value="<?= $anota['id']?>"> Excluir </button>
                    </div>
                </section>";

            <?php } ?>
                      
        <?php } ?>
    </body>
</html>
    